(clear)
(printout t "---NEW-------------------------------" crlf)
(load "headers.clp")
(load "MAIN-rules.clp")
(load "PERCEPT-MANAGER.clp")
(load "DRIVER-AGENT.clp")
(load "PrintDecisionAndDeleteInstantaneousPerceptions.clp")
(load "initials.clp")
(load "maneuverValidityASK.clp")
(reset)
(run 120)
